# Generated by Django 3.0.5 on 2022-12-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='level',
        ),
    ]
