# Generated by Django 3.0.5 on 2022-11-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
    ]
