# Generated by Django 4.0.2 on 2022-11-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library1',
            name='book_image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='library1',
            name='file',
            field=models.FileField(default='', upload_to='library'),
        ),
    ]
