# Generated by Django 4.0.2 on 2022-11-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_library1_book_image_library1_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library1',
            name='file',
            field=models.FileField(blank=True, upload_to='library'),
        ),
    ]
