# Generated by Django 4.0.2 on 2022-11-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_library1_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library1',
        ),
        migrations.RemoveField(
            model_name='library',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='library',
            name='booktitle',
        ),
        migrations.RemoveField(
            model_name='library',
            name='course',
        ),
        migrations.AddField(
            model_name='library',
            name='cover',
            field=models.ImageField(blank=True, upload_to='library/image'),
        ),
        migrations.AddField(
            model_name='library',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='pdf',
            field=models.FileField(blank=True, upload_to='library/Files'),
        ),
        migrations.AddField(
            model_name='library',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
