# Generated by Django 3.0.5 on 2022-11-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_course_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
    ]
