# Generated by Django 3.0.5 on 2022-12-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20221205_1812'),
        ('exam', '0017_auto_20221129_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
            preserve_default=False,
        ),
    ]
