# Generated by Django 3.0.5 on 2022-12-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_section_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='student',
            new_name='levels',
        ),
    ]
