# Generated by Django 3.0.5 on 2022-12-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_auto_20221205_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='levels',
            new_name='level',
        ),
    ]
