# Generated by Django 3.0.5 on 2022-12-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_auto_20221205_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levels',
            old_name='name',
            new_name='level',
        ),
    ]
