# Generated by Django 3.0.5 on 2022-12-12 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20221212_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.Subject'),
            preserve_default=False,
        ),
    ]
