# Generated by Django 3.0.5 on 2022-12-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_course_subject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subject_name',
            new_name='subject',
        ),
    ]
