# Generated by Django 3.0.5 on 2022-11-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacherassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherassignment',
            old_name='subject',
            new_name='course',
        ),
    ]
