# Generated by Django 3.0.5 on 2022-12-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gradelevels',
            field=models.TextField(blank=True, choices=[('Grade 5', 'Grade 5'), ('Grade 3', 'Grade 3'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 6', 'Grade 6'), ('Grade 4', 'Grade 4'), ('Kindergarten', 'Kindergarten')], max_length=20),
        ),
    ]
