# Generated by Django 3.0.5 on 2022-11-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gradelevels',
            field=models.TextField(blank=True, choices=[('Grade 4', 'Grade 4'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 1', 'Grade 1'), ('Grade 5', 'Grade 5'), ('Kindergarten', 'Kindergarten'), ('Grade 6', 'Grade 6')], max_length=20),
        ),
    ]
