# Generated by Django 4.1.2 on 2022-12-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20221212_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bmi',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
