# Generated by Django 4.1.2 on 2022-12-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20221205_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gradelevels',
            field=models.TextField(blank=True, choices=[('Grade 3', 'Grade 3'), ('Grade 5', 'Grade 5'), ('Grade 4', 'Grade 4'), ('Grade 2', 'Grade 2'), ('Grade 6', 'Grade 6'), ('Grade 1', 'Grade 1'), ('Kindergarten', 'Kindergarten')], max_length=20),
        ),
    ]
