# Generated by Django 4.0.2 on 2022-12-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bmi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
