# Generated by Django 4.1.2 on 2022-12-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20221129_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gradelevels',
            field=models.TextField(blank=True, choices=[('Grade 2', 'Grade 2'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 4', 'Grade 4'), ('Grade 3', 'Grade 3'), ('Grade 1', 'Grade 1'), ('Kindergarten', 'Kindergarten')], max_length=20),
        ),
    ]
