# Generated by Django 4.1.2 on 2022-12-15 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20221212_1526'),
        ('student', '0005_levels_alter_student_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='documents/studentsubmission/')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherassignment')),
            ],
        ),
    ]
