# Generated by Django 3.0.5 on 2022-12-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_gradelevels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gradelevels',
            field=models.TextField(blank=True, choices=[('Grade 2', 'Grade 2'), ('Kindergarten', 'Kindergarten'), ('Grade 4', 'Grade 4'), ('Grade 3', 'Grade 3'), ('Grade 1', 'Grade 1'), ('Grade 6', 'Grade 6'), ('Grade 5', 'Grade 5')], max_length=20),
        ),
    ]
