# Generated by Django 4.1.2 on 2022-12-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentasssubmit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentasssubmit',
            name='instruction',
        ),
        migrations.AlterField(
            model_name='studentasssubmit',
            name='upload',
            field=models.FileField(upload_to='documents/submission/'),
        ),
    ]
